### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by evbogue** [ssbc/ssb-ebt#3]
I get this sometimes when replicating using ebt, while syncing a ton of messages.

```
exports.receiveMessage = function (state, msg) {
                                  ^

RangeError: Maximum call stack size exceeded
    at Object.exports.receiveMessage (/home/ev/ssssb/node_modules/epidemic-broadcast-trees/state.js:91:35)
    at cb (/home/ev/ssssb/node_modules/epidemic-broadcast-trees/index.js:105:61)
    at source (/home/ev/ssssb/node_modules/muxrpc/pull-weird.js:46:30)
    at cb (/home/ev/ssssb/node_modules/epidemic-broadcast-trees/index.js:120:15)
    at source (/home/ev/ssssb/node_modules/muxrpc/pull-weird.js:46:30)
    at cb (/home/ev/ssssb/node_modules/epidemic-broadcast-trees/index.js:120:15)
    at source (/home/ev/ssssb/node_modules/muxrpc/pull-weird.js:46:30)
    at cb (/home/ev/ssssb/node_modules/epidemic-broadcast-trees/index.js:120:15)
    at source (/home/ev/ssssb/node_modules/muxrpc/pull-weird.js:46:30)
    at cb (/home/ev/ssssb/node_modules/epidemic-broadcast-trees/index.js:120:15)
```

**Comment by dominictarr** [comment]
were did you install epidemic-broadcast-trees from? 3.0.0 should be good.

**Comment by dominictarr** [comment]
but I previously pushed a commit (unpublished) that had this problem, reverted it though but you may have pulled that from git.

**Comment by evbogue** [comment]
@dominictarr This is on ssb-ebt@1.3.1, which is using  `"epidemic-broadcast-trees": "^3.0.0"`
