### ISSUE TITLE
sbot.getVectorClock is not a function

### ISSUE THREAD

**Issue by nichoth** [ssbc/ssb-ebt#63]
See the example -- https://github.com/planetary-social/planetary-pub/blob/main/index.js#L12

Does this depend on another secret-stack plugin being added?

```
$ node index.js

planetary-pub(main) nick$ node index.js 
/Users/nick/code/planetary-pub/node_modules/ssb-ebt/index.js:122
  sbot.getVectorClock((err, clock) => {
       ^

TypeError: sbot.getVectorClock is not a function
    at Object.exports.init (/Users/nick/code/planetary-pub/node_modules/ssb-ebt/index.js:122:8)
    at /Users/nick/code/planetary-pub/node_modules/secret-stack/lib/api.js:27:34
    at Array.forEach (<anonymous>)
    at create (/Users/nick/code/planetary-pub/node_modules/secret-stack/lib/api.js:26:24)
    at Object.<anonymous> (/Users/nick/code/planetary-pub/index.js:13:6)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
```

**Comment by nichoth** [comment]
This is normally added by `ssb-db`

https://github.com/ssbc/ssb-db/blob/b2256fd7e3e6e3804ca5f388b3fc351312250d05/README.md#dbgetvectorclock-async

**Comment by staltz** [comment]
Can we close this one?
